AWSTemplateFormatVersion: "2010-09-09"
Description: A Simple S3 Bucket
Resources:
  MyHW1Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: 
        Fn::Join: ["-", [!If [RegionIsUSEast1, !Ref "AWS::AccountId", !Ref "AWS::Region"], Ref: NameParam]]

Parameters:
  NameParam: 
    Type: String

Conditions:
  RegionIsUSEast1: !Equals [!Ref "AWS::Region", "us-east-1"]
